# Generated by Django 4.2.5 on 2025-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', 'add_category_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Срочно')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'К выполнению'), ('IN_PROGRESS', 'В процессе'), ('REVIEW', 'На проверке'), ('DONE', 'Выполнено')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
